# Tessera Tutorial at useR! 2015 #

The Tessera team will be presenting an interactive tutorial at [useR! 2015](http://user2015.math.aau.dk) in Aalborg Denmark on June 30, 2015.

## Links for the Tutorial

- [Slides](http://ml.stat.purdue.edu/user2015/Tessera-aalborg-slides.html)
- [Housing example code](https://raw.githubusercontent.com/tesseradata/docs-UseR2015/gh-pages/R/housing.R) (note that you can equivalently use the code in the slides)
- [Taxi example code](https://raw.githubusercontent.com/tesseradata/docs-UseR2015/gh-pages/R/taxi.R) and line to [rate code information](http://www.nyc.gov/html/tlc/html/passenger/taxicab_rate.shtml)

## Download Tutorial Materials ##

To avoid network issues at the tutorial and to help get things started off smoothly, please download the required packages and data sets listed below prior to the tutorial.  Additional materials such as slides and example code will be made available at the time of the tutorial.

1. If you do not already have the most recent version of R, (version 3.2), please [download](http://cran.r-project.org) and install it.

2. You will need a recent version of the Firefox or Chrome browser installed on your computer.

3. Open R and execute the following commands to install Tessera and other libraries you'll need for the tutorials:

```r
install.packages(c("maps", "ggplot2", "gridExtra", "lubridate", "geosphere", "devtools"))
devtools::install_github("tesseradata/datadr")
devtools::install_github("tesseradata/trelliscope")
devtools::install_github("hafen/housingData")
devtools::install_github("bokeh/rbokeh")
```

**For Windows users:**  when installing `devtools`, you may notice the following warning, which you can ignore:

```r
> library(devtools)
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.x was found. (Only the following incompatible version(s) of Rtools were found:3.2)
Please download and install Rtools 3.1 from http://cran.r-project.org/bin/windows/Rtools/ and then run find_rtools().
```

To test your installation, you can load R and try the following commands:

```r
library(trelliscope)
library(rbokeh)
library(housingData)

panel <- function(x)
  figure() %>% ly_points(time, medListPriceSqft, data = x)

housing %>%
  qtrellis(by = c("county", "state"), panel, layout = c(2, 4))
```

This should bring up an interactive trelliscope display in your web browser.

4. Download the NYC Taxi sample data and unzip it on your computer: [taxiOneWeek.csv.zip](http://ml.stat.purdue.edu/user2015/taxiOneWeek.csv.zip)

## Additional Reading Material ##

If you want to read up on any of the Tessera components prior to the tutorial, you can look at the [references section on tessera.io](http://tessera.io/#references).

<!-- 6. The zip file contains a folder called **exercises**.  Set your working directory in R to this folder,
using something like `setwd("mypaths/exercises")`.  The **exercises** folder
contains a folder for each of the three exercises:  **power_exercise**, **netflow_exercise**, and **housing_exercise**.
Each exercise folder has a single **.R** file which contains the code for the exercise. Open that
file in your editor of choice and begin! -->

#### We look forward to seeing you at useR!
